spring:
  kafka:
    uri: localhost:29092
    bootstrap-servers: ${spring.kafka.uri}
    offset:
      reset:
        value: latest
    enable:
      auto:
        commit:
          config:
            value: false
    idle:
      timeout: 1000
  elasticsearch:
    uris: localhost:9200


springdoc:
  swagger-ui:
    path: /swagger-ui   # swagger-ui custom path
  api-docs:
    path: /api-docs     # /api-docs endpoint custom path (json format)

server:
  port: 8999

